# O docker-compose.yml consiste em um programa que define as condições de criação e execução de múltiplas imagens pertencentes a um mesmo projeto.
# As imagens podem tanto ser criadas exclusivamente pelo próprio docker-compose (ao baixar uma imagem, pelo parâmetro 'image'), como podem ser criadas em conjunto
# com o dockerfile, sendo este utilizado quando desejamos criar nossa própria imagem de forma mais maleável (mesmo que para isso precisemos utilizar outra imagem como base)

# Observação: uma vez que determinado parâmetro tenha sido comentado, ele só será comentado novamente caso apresente alguma particularidade.

# Versão do docker-compose a ser utilizada
version: "3.7"

# Define os serviços do projeto (containers a serem criados)
services:
  # Aqui definiremos as condições de inicialização do serviço de api em flask do dataviewer: 
  api-lop:
    image: dataviewer/api-dataviewer:$(TAG)-api-lop
    container_name: container-api-lop
    # Define o comportamento do container caso ele venha a cair. Neste caso, definimos que sempre que ele cair, irá ser inicializado novamente
    restart: always 
    # Define que só irá ser inicializado após o serviço db_lop ser inicalizado (isso não quer dizer que ele espera o container db_lop ser totalmente construído)
    depends_on:
      - db-lop 
      - db-users
    ports:
      # Como padrão do Flask, associamos a porta local 5000 como sendo a porta 5000 do container
      - "5000:5000" 
    # Não sei exatamente como isso funciona, nem se isso é necessário, mas estamos linkando a todos os serviços que será necessário uma comunicação direta
    links:
      - db-lop
      - db-users
    # Define a qual network o serviço irá se conectar (por padrão, o docker-compose já cria uma network sem precisar especificar, mas pode ser que mais pra frente seja necessário por conta do nginx)
    networks:
      - backend
      
  # Aqui definiremos as condições de inicialização do serviço de banco de dados do lop no dataviewer:    
  db-lop:
    # Esse serviço não contem o parâmetro build, pois utilizamos diretamente uma imagem pré-existente, fazendo as configurações pertinentes no próprio docker-compose
    image: dataviewer/api-dataviewer:$(TAG)-db-lop
    # Parâmetro encontrado na documentação do postgres p/ o docker
    hostname: postgres
    container_name: db-lop-container
    restart: always
    # A porta padrão do postgres é a 5432
    ports:
      - "5432:5432"
    # talvez essa linha não seja necessária, mas garante que a porta 5432 está exposta para todos os containers
    expose:
      - 5432
    volumes:
      # Define onde o script de inicialização das tabelas está localizado.
      - create_database_dataviewer_lop.sql:/docker-entrypoint-initdb.d/create_database_dataviewer_lop.sql
      # Onde os dados do banco de dados estarão armazenados. Essa pasta não existe no repositório, mas ela é criada na máquina local.
      - ./container-lop-db/data:/var/lib/postgresql/data-lop
    networks:
      - backend
    # Os comentários abaixo eram para que outros serviços pudessem verificar quando este container estivesse 100% construído, como condição de inicialização de outros serviços. Por enquanto, não está sendo utilizado
    # healthcheck: # acho q isso n vai ser necessário
    #  test: ["CMD-SHELL", "pg_isready -U postgres"] 
    #  interval: 5s
    #  timeout: 5s
    #  retries: 5
      
  # Aqui definiremos as condições de inicialização do serviço de atualização do nosso banco de dados do lop no dataviewer    
  update-db-lop:
    image: dataviewer/api-dataviewer:$(TAG)-update-db-lop    
    restart: always
    depends_on:
      - db-lop
      # Os comentários abaixo eram para inicializar o container desta api apenas quando o container do sqldb estivesse totalmente construído. Contudo, por enquanto estamos deixando isso de lado
      #db_lop: 
        #condition: service_healthy
    ports:
      - "3000:3000" 
    links:
      - db-lop
    networks:
      - backend
    # O comando abaixo não será utilizado, estamos guardando por enquanto apenas para termos uma alternativa de onde recorrer caso seja necessário aguardar o container do banco de dados estar 100% construído
    #command: ["./scripts/db/wait-for-it.sh", 

  api-users:
    image: dataviewer/api-dataviewer:$(TAG)-api-users
    container_name: api-users-container # define o nome do container
    restart: always # reinicia o container sempre 
    depends_on: 
      - db-users # especifica que o container usersdb precisa ser inicializado antes
    ports:
      - "5050:5050"
    links:
      - db-users
    networks:
      - backend

  db-users:
    image: dataviewer/api-dataviewer:$(TAG)-db-users
    hostname: postgres
    container_name: db-users-container
    restart: always
    ports:
      - "5431:5432"
    expose:
      - 5431
    volumes:
      - create_database_dataviewer_users.sql:/docker-entrypoint-initdb.d/create_database_dataviewer_users.sql
      - ./container-db-users/data:/var/lib/postgresql/data-users
    networks:
      - backend
      
  nginx:
    image: dataviewer/api-dataviewer:$(TAG)-nginx
    depends_on:
      - api-users
      - api-lop
    container_name: nginx-container
    restart: always
    ports:
      - "443:443"
    networks:
      - backend
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email erros.dataviewer@gmail.com --agree-tos --no-eff-email --staging -d dataviewer.natalnet.br  -d www.dataviewer.natalnet.br

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/admin/api-dataviewer/views/
      o: bind


# Cria a network a ser utilizada no projeto
networks:
  backend:
    driver: "bridge"
