#Em /home/admin/api-dataviewer executar
get_files:
	curl -O https://github.com/Natalnet/api-dataviewer/blob/main/scripts/compose-prodution/docker-compose.yml
	curl -O https://github.com/Natalnet/api-dataviewer/blob/main/scripts/db/create_database_dataviewer_lop.sql
	curl -O https://github.com/Natalnet/api-dataviewer/blob/main/scripts/db/create_database_dataviewer_users.sql
get_env: 
	curl -O https://github.com/vilsonrodrigues/RESTAPIDataView/blob/main/env.zip
	unzip env.zip
	rm env.zip
#No console usar a seguinte sequência de comandos para subir o compose
#make
#make get_env
