#docker-compose que entrará para a fase de produção
# Versão do docker-compose a ser utilizada
version: '3.9'

# Define os serviços do projeto (containers a serem criados)
services:
  # Serviço de API 
  api-node:
    build: ./container-api-node/ 
    ports:
      - 3333:3333
    container_name: api-node
    command: yarn start
  
  #Banco de dados MongoDB
  mongo:
    image: mongo
    container_name: mongodb
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${USER_DB_MONGO}
      MONGO_INITDB_ROOT_PASSWORD: ${PASSWORD_DB_MONGO}
    restart: always

  #Proxy Reverso
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    depends_on:
      - api-node
    container_name: nginx-container
    restart: always
    ports:
      - "443:443"
      - "80:80"
    expose:
      - 80
      - 443
    # Volumes necessários para sua associação com o certbot e consequente autenticação.
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  # O certbot é responsável pela autenticação(tutorial da digitalocean).  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email erros.dataviewer@gmail.com --agree-tos --no-eff-email --staging -d dataviewer.natalnet.br -d www.dataviewer.natalnet.br
    logging:
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/admin/api-dataviewer/views/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /home/admin/api-dataviewer/dhparam/
      o: bind